<a href="https://colab.research.google.com/github/Prabhu5460/Prabhu5460/blob/main/Copy_of_Copy_of_mfds_assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is Python Jupyter notebook for MFDS Assignment 1

The references take for this work are from:
1. https://www.codesansar.com/numerical-methods/gauss-elimination-method-python-program.htm
2. https://www.codesansar.com/numerical-methods/python-program-gauss-seidel-iteration-method.htm
3. https://www.codesansar.com/numerical-methods/python-program-jacobi-iteration-method.htm

As a part of Assignment 1, we are given task to implement 3 methods of solving linear systems of equations. They are:
1. Gauss Elimination
2. Gauss Seidel Method
3. Gauss Jacobi Method

In Question 1, the Gaussian Elimination method is showcased. It takes randomly generated input matrices of size [n x (n+1)] in the form of augmented matrix. Then Forward elimination and back substitution is applied as a part of Gauss elimination method. The solution of the system is obtained via both Pivoting and Non-Pivoting way. The user can provide the significant digits required for the whole process.

In Question 2, the Gauss Seidel and Jacobi methods are showcased. This takes randomly generated diagonally dominant matrices of size [3 x 4] in the form of augmented matrix. Then the convergence criteria is used to arrive at the solution obtained from the two methods.

Question 1: Write a code to perform Gauss elimination with and without pivoting for a 2 x 2 system, taking the number of significant digits (d) to be considered as user input. Using the code, solve the 2 x 2 system with random coefficients for d = 3, 4, 5 and 6.

In [ ]:
import numpy as np
import sys
import copy
import math
from numpy.random import RandomState
np.set_printoptions(suppress=True)
random_state = RandomState(1240)

In [ ]:
# Round numbers according to significant digits
def my_round(d, x):
	return d - int(math.floor(math.log10(abs(x)))) - 1

In [ ]:
# Round numbers according to significant digits
def my_round(d, x):
	return d - int(math.floor(math.log10(abs(x)))) - 1

print("Welcome to the Gaussian Elimination method for linear systems!")

# Reading the size of linear system
n = int(input('Enter the size of linear system: '))

# Reading precision required by user
d = int(input('Enter the precision value d: '))


Welcome to the Gaussian Elimination method for linear systems!
Enter the size of linear system: 2
Enter the precision value d: 4


In [ ]:
a = 10 * random_state.rand(n, n+1)
for i in range(n):
	for j in range(n+1):
		a[i][j] = np.around(a[i][j], decimals = my_round(d, a[i][j]))
print(a)

c = copy.deepcopy(a)
e = copy.deepcopy(a)

[[1.83  2.415 9.499]
 [1.526 2.852 7.084]]


In [ ]:
print("\nAugmented matrix with precision set by the user:")
print(a)


Augmented matrix with precision set by the user:
[[1.83  2.415 9.499]
 [1.526 2.852 7.084]]


In [ ]:
def swap_rows(row_1, row_2):
	row_1 = row_1 - row_2
	row_2 = row_1 + row_2
	row_1 = row_2 - row_1
	return row_1, row_2

In [ ]:
"""
def swap_rows_2(row_1, row_2):
	return row_2, row_1
"""

In [ ]:
def partially_pivot(matrix):
	# Partially pivoting the input matrix

	# If a row except first row has larger value in first column
	# then swap that row with first row
	column_1 = matrix[:,0]
	max_index = np.argmax(column_1)
	if max_index != 0:
		matrix[0], matrix[max_index] = swap_rows(matrix[0], matrix[max_index])

	print("\nThe pivoted matrix is:\n"+str(matrix)+"\n")
	
	""" Below logic is to sort all rows based on first column
	for i in range(n):     
		for j in range(i+1, n):
			if arr1[j][0] > arr1[i][0]:
				arr1[i] = arr1[i] - arr1[j]
				arr1[j] = arr1[i] + arr1[j]
				arr1[i] = arr1[j] - arr1[i]"""
				
	return matrix

In [ ]:
def forward_elimination(matrix, size, pivot = False):
	for i in range(size):	
		for j in range(i+1, size):
			ratio = matrix[j][i]/matrix[i][i]
			ratio = round(ratio, my_round(d,ratio))

			for k in range(size+1):
				matrix[j][k] = matrix[j][k] - round(ratio* matrix[i][k], my_round(d,ratio* matrix[i][k]))

		if pivot:
			# Below logic executes pivoting of intermediate rows (for partial pivoting)
			if i+1 != size:
				col = np.argmax(abs(matrix[i+1:, i+1]))
				matrix[i+1], matrix[col+i+1] = swap_rows(matrix[i+1], matrix[col+i+1])

	for k in range(size):
		for l in range(k, size+1):
			matrix[k][l] = np.around(matrix[k][l], decimals = my_round(d, matrix[k][l]))

	return matrix

In [ ]:
def back_substitution(y, size, arr):
	# Back Substitution
	y[size-1] = arr[size-1][size]/arr[size-1][size-1]

	for i in range(size-2,-1,-1):
		y[i] = arr[i][size]
		
		for j in range(i+1,size):
			y[i] = y[i] - round(arr[i][j]*y[j], my_round(d, arr[i][j]*y[j]))
		
		y[i] = y[i]/arr[i][i]
	
	for i in range(size):
		y[i] = round(y[i], my_round(d, y[i]))

	return y

In [ ]:
def print_solution(z, size, precision):
	# Displaying solution
	print('\nThe solution obtained from Gaussian Elimination is: ')
	for i in range(n):
		print('X{} = {}' .format(i, z[i]), end = '\n')

In [ ]:
def ge_with_pivot(aug_mat, size, precision):
	# Applying Gauss Elimination (With Partial Pivoting)
	sol = np.zeros(n)
	pivot_mat = partially_pivot(aug_mat) # Pivot first row

	fe_mat_piv = forward_elimination(pivot_mat, size, True)
	
	ge_mat = back_substitution(sol, size, fe_mat_piv)
	
	return ge_mat

In [ ]:
def ge_without_pivot(aug_mat, size, precision):
	# Applying Gauss Elimination (Without Partial Pivoting)
	
	# Check validity of input to avoid divide by zero
	for i in range(size):
		if aug_mat[i][i] == 0.0:
			sys.exit('Divide by zero detected!') 
	sol = np.zeros(n)
	fe_mat_non_piv = forward_elimination(aug_mat, size)
		
	ge_mat = back_substitution(sol, size, fe_mat_non_piv)
	
	return ge_mat

In [ ]:
sol_piv = ge_with_pivot(c, n, d)
sol_non_piv = ge_without_pivot(e, n, d)

print_solution(sol_piv, n, d)
print_solution(sol_non_piv, n, d)


The pivoted matrix is:
[[7.073 5.964 6.676]
 [5.956 6.674 9.998]]


The solution obtained from Gaussian Elimination is: 
X0 = -1.29
X1 = 2.649

The solution obtained from Gaussian Elimination is: 
X0 = -1.29
X1 = 2.648


Question 2: Write a code to perform
a) Gauss Jacobi method
b) Gauss Seidel method
for a 3 x 3 system by checking the convergence criteria using a suitable norm.
Test the method on a random 3 x 3 system, which is diagonally dominant
and check your results. A comparison between the two methods should be
presented in tabular form. The stopping criteria could be taken as the low-
est iteration number when the relative percentage error is less than 1%.

Generate a random matrix of size 3 x 3 which cannot be made diagonally
dominant and check if the iterates converge. The random entries generated
should be of the form n.dddd

In [ ]:
import numpy as np
import sys
import copy
import math
from numpy.random import RandomState
np.set_printoptions(suppress=True)
random_state = RandomState(1240)

In [ ]:
diag_dom_condition = False

# Generate diagonally dominant matrix
while diag_dom_condition != True:
	a = 20 * random_state.rand(3, 4)
	a = np.around(a, decimals=4)
	diag_dom_condition = (np.abs(a[0][0])>np.abs(a[0][1])+np.abs(a[0][2])) and \
	(np.abs(a[1][1])>np.abs(a[1][0])+np.abs(a[1][2])) and \
	(np.abs(a[2][2])>np.abs(a[2][0])+np.abs(a[2][1]))

print(a)

[[18.4714 10.7758  4.4105  5.6016]
 [ 2.4005 18.846  12.7583  5.8773]
 [ 3.8367  6.1014 13.5922 15.5535]]


In [ ]:
# Defining equations to be solved
# in diagonally dominant form
f1 = lambda x,y,z: (a[0][3]-a[0][1]*y-a[0][2]*z)/a[0][0]
f2 = lambda x,y,z: (a[1][3]-a[1][0]*x-a[1][2]*z)/a[1][1]
f3 = lambda x,y,z: (a[2][3]-a[2][0]*x-a[2][1]*y)/a[2][2]

In [ ]:
# Implement Gauss Seidal Method
def gauss_seidal(x,y,z,e):
	count = 1
	condition = True
	print('\nCount\tx\ty\tz\n')
	while condition:
		# In Gauss Seidal, newest available
		# values of variables are used
		x1 = round(f1(x,y,z),4)
		y1 = round(f2(x1,y,z),4)
		z1 = round(f3(x1,y1,z),4)
		print('%d\t%0.4f\t%0.4f\t%0.4f\n' %(count, x1,y1,z1))
		e1 = abs((x-x1)/x1);
		e2 = abs((y-y1)/y1);
		e3 = abs((z-z1)/z1);

		count += 1
		x = x1
		y = y1
		z = z1

		condition = e1>e and e2>e and e3>e
	print('\nSolution from Gauss Seidal Method: x=%0.4f, y=%0.4f and z = %0.4f\n'% (x1,y1,z1))

In [ ]:
# Implement Gauss Jacobi Method
def gauss_jacobi(x,y,z,e):
	count = 1
	condition = True
	print('\nCount\tx\ty\tz\n')
	while condition:
		# In Gauss Jacobi, values of variables
		# available from last iteration are used
		x1 = round(f1(x,y,z),4)
		y1 = round(f2(x,y,z),4)
		z1 = round(f3(x,y,z),4)
		print('%d\t%0.4f\t%0.4f\t%0.4f\n' %(count, x1,y1,z1))
		e1 = abs((x-x1)/x1);
		e2 = abs((y-y1)/y1);
		e3 = abs((z-z1)/z1);

		count += 1
		x = x1
		y = y1
		z = z1

		condition = e1>e and e2>e and e3>e

	print('\nSolution from Gauss Jacobi Method: x=%0.4f, y=%0.4f and z = %0.4f\n'% (x1,y1,z1))

In [ ]:
# Initial setup
x0 = 0
y0 = 0
z0 = 0

# Reading tolerable error
e = float(input('Enter tolerance value required (in %): '))/100

Enter tolerance value required (in %): 1


In [ ]:
gauss_seidal(x0,y0,z0,e)
gauss_jacobi(x0,y0,z0,e)


Count	x	y	z

1	0.3033	0.2732	0.9360

2	-0.0796	-0.3117	1.3067

3	0.1731	-0.5948	1.3624

4	0.3249	-0.6518	1.3452

5	0.3623	-0.6450	1.3316

6	0.3616	-0.6357	1.3276


Solution from Gauss Seidal Method: x=0.3616, y=-0.6357 and z = 1.3276


Count	x	y	z

1	0.3033	0.3119	1.1443

2	-0.1519	-0.5014	0.9187

3	0.3764	-0.2907	1.4122

4	0.1356	-0.6921	1.1685

5	0.4280	-0.4965	1.4167

6	0.2546	-0.7017	1.2464

7	0.4150	-0.5644	1.3874

8	0.3012	-0.6802	1.2805

9	0.3943	-0.5934	1.3646

10	0.3236	-0.6622	1.2994

11	0.3793	-0.6090	1.3502

12	0.3361	-0.6505	1.3106

13	0.3698	-0.6182	1.3414

14	0.3436	-0.6433	1.3174

15	0.3640	-0.6238	1.3361

16	0.3481	-0.6390	1.3216

17	0.3605	-0.6272	1.3329


Solution from Gauss Jacobi Method: x=0.3605, y=-0.6272 and z = 1.3329

